language: node_js
node_js:
  - "8"
before_install:
  - "cd client && npm install && cd ../"
script:
  - "npm run build"
  - "cd client && npm run build"
cache:
  directories:
    - "node_modules"
    - "client/node_modules"
