dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - "8"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - "cd client && npm install && cd ../"
script:
  - "npm run build"
  - "cd client && npm run ci"
cache:
  directories:
    - "node_modules"
    - "client/node_modules"
